language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  - composer install -n

script: phpunit
